<a href="https://colab.research.google.com/github/arumugammani02/Numpy_tasks/blob/main/Numpy_tasks_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
z= np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
z= np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
"import numpy.info(numpy.add)"

'import numpy.info(numpy.add)'

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a=np.arange(20)
a=a[::-1]
print(a)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.random((3,3,3))
print(a)

[[[0.78331418 0.61775688 0.02231101]
  [0.6443836  0.11616513 0.12259868]
  [0.83336902 0.50115545 0.52528513]]

 [[0.63452608 0.48766644 0.4195335 ]
  [0.57343748 0.52076418 0.30172581]
  [0.47727234 0.32602188 0.76469524]]

 [[0.04799002 0.08629319 0.24372934]
  [0.07228542 0.01421087 0.2721598 ]
  [0.82988291 0.56022302 0.28344429]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
A=np.random.random((10,10))
Amin,Amax =A.min(),A.max()
print(Amin,Amax)

0.008883092787802083 0.9960486812751635


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
b=a.mean()
print(b)

0.5009758681052571


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.ones((3,3))
a=np.pad(a, pad_width=1,mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0*np.nan
np.nan==np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3==3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a=np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
arr=np.ones(64,dtype=int)
arr[::2]=0
arr=arr.reshape((8,8))
print(arr)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(z))
print(a)

[[ inf  inf -inf -inf -inf]
 [ inf -inf  inf -inf -inf]
 [ inf  inf  inf -inf  inf]
 [-inf -inf -inf  inf -inf]
 [ inf  inf  inf -inf  inf]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color=np.dtype([('r',np.ubyte),
                ('g',np.ubyte),
                ('b',np.ubyte),
                ('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a=np.arange(11)
a[(3<a)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z
z <- z
1j*z
z/1/1


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a=np.random.uniform(-10,+10,10)
print(np.where(a>0,np.ceil(a),np.floor(a)))

[  1.   8.  -2.  -7.  -4.  -7.   1. -10. -10.   2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a1=np.random.randint(0,10,10)
a2=np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[0 2 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults=np.seterr(all='ignore')
a=np.ones(1)/0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-10-27
2022-10-28
2022-10-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.ones(3)*1
B = np.ones(3)*1
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(a//1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))

[0. 9. 1. 3. 7. 6. 8. 9. 0. 2.]
[0. 9. 1. 3. 7. 6. 8. 9. 0. 2.]
[0. 9. 1. 3. 7. 6. 8. 9. 0. 2.]
[0 9 1 3 7 6 8 9 0 2]
[0. 9. 1. 3. 7. 6. 8. 9. 0. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.zeros((5,5))
a=a+np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for x in range(10):
    yield x
a=np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a=np.random.random(10)
a.sort()
print(a)

[0.00885265 0.18890485 0.23368123 0.35249824 0.46039037 0.55608883
 0.74029975 0.87678234 0.93453432 0.99178131]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
equal=np.allclose(a,b)
print(equal)

True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a=np.zeros(10)
a.flags.writeable = False
a[0] = 1 


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
b=np.sqrt(x**2+y**2)
c=np.arctan2(x,y)
print(b)
print(c)

[1.05622486 1.04611208 0.61482621 0.71980218 0.91359423 1.22020785
 0.60586443 0.34253584 0.55722451 0.96022544]
[0.33464253 0.47974089 0.950741   1.3675094  1.04842202 0.72340751
 0.69215698 0.22681404 0.04924839 1.21239866]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.random.random(10)
a[a.argmax()]=0
print(a)

[0.35678222 0.08584794 0.         0.95610705 0.98337295 0.33923718
 0.81545409 0.26759907 0.20253697 0.02402802]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a=np.arange(8)
b=a+0.5
c=1.0/np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in[np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in[np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float('inf'))
a=np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a=np.arange(100)
b=np.random.uniform(0,100)
index=(np.abs(a-b)).argmin()
print(a[index])

65


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a=np.zeros(10,[('position', [('x',float,1),
                            ('y',float,1)]),
              ('color',[('r',float,1),
                        ('g',float,1),
                        ('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import scipy
import scipy.spatial

a=np.random.random((10,2))
b=scipy.spatial.distance.cdist(a,a)
print(b)

[[0.         0.67033435 0.64398113 0.25728395 0.59036353 0.41999317
  0.1568337  0.17049324 0.61478762 0.57259491]
 [0.67033435 0.         0.26938912 0.64166041 0.35072307 0.38672848
  0.67300868 0.49993405 0.37673165 0.41850195]
 [0.64398113 0.26938912 0.         0.51307162 0.57233404 0.23750428
  0.58354389 0.49502986 0.11558306 0.17194075]
 [0.25728395 0.64166041 0.51307162 0.         0.69865454 0.27855724
  0.10858522 0.26693568 0.44431478 0.38754892]
 [0.59036353 0.35072307 0.57233404 0.69865454 0.         0.55281381
  0.67351016 0.45057874 0.64996959 0.66588965]
 [0.41999317 0.38672848 0.23750428 0.27855724 0.55281381 0.
  0.34627719 0.29424096 0.19524067 0.16125208]
 [0.1568337  0.67300868 0.58354389 0.10858522 0.67351016 0.34627719
  0.         0.22325277 0.52911738 0.47699305]
 [0.17049324 0.49993405 0.49502986 0.26693568 0.45057874 0.29424096
  0.22325277 0.         0.48590251 0.45532195]
 [0.61478762 0.37673165 0.11558306 0.44431478 0.64996959 0.19524067
  0.52911738 0.48590

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=(np.random.rand(10)*100).astype(np.float32)
b=a.view(np.int32)
b[:]=a
print(y)

[0.99763371 0.92802124 0.35726333 0.14532061 0.45582798 0.9146123
 0.46643759 0.33376274 0.5565489  0.33682228]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
 ''')
a=np.genfromtxt(s,delimiter=',',dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(a):
  print(index,value)
for index in np.ndindex(a.shape):
  print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
a=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
b=np.exp(-((a-mu)**2/(2.0*sigma**2)))
print(b)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=10
p=3
a=np.zeros((n,n))
np.put(a,np.random.choice(range(n*n),p,replace=False),1)
print(a)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
a=np.random.rand(5,10)
b=a-a.mean(axis=1,keepdims=True)
print(b)

[[-0.20507452  0.1897321  -0.12230399 -0.26998692  0.57939155  0.25018842
  -0.18743286 -0.12840521 -0.13527569  0.02916712]
 [ 0.43923188  0.42183322  0.21845431 -0.1248251   0.010215   -0.15238246
  -0.1705897  -0.42282798  0.06350818 -0.28261734]
 [ 0.19273709 -0.11129268 -0.0483472   0.09895823 -0.16436431 -0.14418992
   0.19883551  0.32596505 -0.02211379 -0.32618798]
 [ 0.1820764  -0.14814087  0.43213651  0.09453322 -0.40707909 -0.04561974
   0.0950456  -0.01326251 -0.49863318  0.30894366]
 [-0.24041772 -0.14723316  0.32689798  0.26725544 -0.26931789 -0.24187264
  -0.10115599  0.29202973  0.19007765 -0.0762634 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[6 7 1]
 [2 3 1]
 [6 3 0]]
[[2 3 1]
 [6 3 0]
 [6 7 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
A=np.random.uniform(0,1,10)
a=0.5
m=A.flat[np.abs(A-a).argmin()]
print(m)

0.43359123325239646


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
  def _new_(cls,array,name='no name'):
    obj = np.asarray(array).view(cls)
    obj.name=name
    return obj
  def _array_finalize_(self,obj):
    if obj is None:return
    self.name = getattr(obj,'name','no name')

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
a+=np.bincount(b,minlength=len(a))
print(a)

[2. 3. 5. 3. 4. 2. 3. 2. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=[1,2,3,4,5,6]
b=[1,2,4,5,7,1]
F=np.bincount(b,a)
print(F)

[0. 7. 2. 0. 3. 4. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h=256,256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n=len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.sum(axis=(-2,-1))
print(sum)

[[44 54 41 44]
 [65 80 57 53]
 [47 32 60 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D=np.random.uniform(0,1,100)
S=np.random.randint(0,1,100)
D_sums=np.bincount(S,weights=D)
D_counts=np.bincount(S)
D_means=D_sums/D_counts
print(D_means)

[0.51040815]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))
np.sum(a*b.T,axis=1)


array([1.7928289 , 1.08113953, 1.0936985 , 0.71640003, 1.64884681])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a=np.array([1,2,3,4,5])
nz=3
a0=np.zeros(len(a)+(len(a)-1)*(nz))
a0[::nz+1]=print(a0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
face=np.random.randint(0,100,(10,3))
F=np.roll(face.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G=np.unique(G)
print(G)

[( 5, 36) ( 5, 98) ( 7, 19) ( 7, 55) (12, 13) (12, 30) (13, 25) (13, 30)
 (13, 53) (17, 34) (17, 57) (19, 55) (25, 53) (30, 41) (30, 99) (34, 57)
 (36, 98) (40, 70) (40, 76) (41, 99) (54, 60) (54, 71) (60, 71) (61, 82)
 (61, 95) (64, 71) (64, 72) (70, 76) (71, 72) (82, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c=np.bincount([1,1,2,3,4,4,6])
a=np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a,n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]=ret[n:]-ret[:-n]
  return ret[n-1:]/n
a=np.arange(20)
print(moving_average(a,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a,window):
  shape=(a.size - window +1, window)
  strides = (a.strides[0],a.strides[0])
  return stride_tricks.as_strided(a, shape=shape, strides=strides)

a=rolling (np.arange(10),3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a=np.random.randint(0,2,100)
np.logical_not(a,out=a)

a=np.random.uniform(-1.0,1.0,100)
np.negative(a,out=a)

array([-0.8890054 , -0.91120167, -0.38664295,  0.38651827,  0.01456271,
        0.60151279, -0.42674565, -0.46857062,  0.2082398 ,  0.2284607 ,
        0.58472532,  0.75907679,  0.88685987,  0.19221758,  0.95964536,
       -0.16554558, -0.00379512, -0.9184992 ,  0.59302899,  0.338944  ,
        0.05867586,  0.50017054,  0.69083684, -0.36789156,  0.52862597,
       -0.21325066, -0.28902932, -0.12687703, -0.12731553,  0.26187317,
        0.35418399,  0.61132607, -0.11357622,  0.34938698, -0.60196235,
        0.49429274, -0.63452307, -0.15166496, -0.48196105,  0.50691612,
        0.14214148,  0.85212136, -0.94202438,  0.48568126, -0.59101945,
       -0.09123693,  0.92047885, -0.11811153, -0.35153141, -0.82857076,
        0.28018893,  0.26912647,  0.42467938, -0.04119757,  0.8101066 ,
        0.42608189,  0.85580751, -0.79565653,  0.83206812, -0.84656397,
       -0.47720509, -0.70575086, -0.11781471,  0.46113033, -0.91295252,
       -0.20986098,  0.53631837,  0.61132129,  0.30765469, -0.74

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(p0,p1,p):
  T=p1 -p0
  L=(T**2).sum(axis=1)
  U=-((p0[:,0]-p[...,0])*T[:,0]+(p0[:,1]-p[...,1])*T[:,1])/L
  U=U.reshape(len(U),1)
  D= p0 + U*T -p
  return np.sqrt((D**2).sum(axis=1))


p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(p0,p1,p))

[ 6.51414784  1.25958766  0.7620473   9.44354992  4.29270635  2.33943578
  6.67955058  1.73838788 15.58188358 12.55629786]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i)for p_i in p]))

[[ 0.50604126 11.34970275  8.38855548 12.89584267  4.58129703  4.71642506
   0.28545651  5.41672764  5.80221104  0.78680189]
 [ 5.02233464 10.89663443 12.45148507 11.95515632  0.1568264   0.64343305
   3.53520599  2.50696568  8.20074571  4.55570026]
 [11.55683961  5.77516585 13.74425074  6.41250853  3.33259994  0.67238796
   3.19658847  4.20851934  6.46862719  5.21145436]
 [ 1.77204165  8.49102875  3.16910248 10.47969008  9.5149679   9.93508038
   4.83822056  5.1525034   0.99598018  4.43060224]
 [10.62847998  1.06397199  5.7907868   0.11497613  3.35317646  7.26995599
   5.29570778  7.49945645  2.10000656  3.01000386]
 [ 2.49093348 10.1105048   4.11125703 12.07826495  8.99423032  8.99747134
   3.60904196  6.48375249  2.41674837  3.36833438]
 [ 8.80163508  7.15611684 12.39981808  8.02060925  1.35215811  0.68028474
   2.46073201  1.8137301   6.2921045   4.09872915]
 [ 2.15455738  3.17510422  1.64743804  5.05319644  9.45097807 11.4386323
   7.56814963  0.1386207   2.65245501  6.44109961]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
A=np.random.uniform(-10,10,(10,2))
shape=(5,5)
fill=0
position=(1,1)


R=np.ones(shape,dtype=z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
As=np.array(list(A.shape)).astype(int)

R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.zeros((len(shape),)).astype(int)
A_start=(P-Rs//2)
A_stop=(P+Rs//2)+Rs%2

R_start=(R_start-np.minimum(A_start,0)).tolist()
A_start=(np.minimum(A_start,0)).tolist()
R_stop=np.minimum(R_start,(R_stop-np.minimum(A_stop-As,0))).tolist()
A_stop=(np.minimum(A_stop,As)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
a=[slice(start,stop) for start,stop in zip(A_start,A_stop)]
R[r] = A[a]
print(A)
print(R)

[[ 7.36697771  9.57394794]
 [ 7.43889854  9.8605231 ]
 [-8.30580222 -8.22205036]
 [ 0.72764867  7.47071038]
 [ 6.35398954 -1.9021156 ]
 [ 9.12477136  0.96054027]
 [ 3.62841597 -1.72938653]
 [ 1.27832362 -6.16362245]
 [ 1.26887997  1.20347626]
 [ 9.18533477  6.93906726]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
A = np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(A,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
A = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(A)
rank=np.linalg.matrix_rank(A)
print(A)

[[0.18150159 0.65930486 0.69653867 0.80720189 0.60273033 0.12093227
  0.59230697 0.8056634  0.67855715 0.52559174]
 [0.13201233 0.6740904  0.01487935 0.55519849 0.77421791 0.404477
  0.78547849 0.23961001 0.00769238 0.10484809]
 [0.96507021 0.57631804 0.68975678 0.15551666 0.09016829 0.96856184
  0.2248673  0.30932566 0.08291347 0.6768611 ]
 [0.20613105 0.18705188 0.77190156 0.71182524 0.4018335  0.79338616
  0.79755696 0.58686601 0.0220538  0.98906233]
 [0.66304183 0.85681098 0.97434326 0.93494341 0.96833735 0.94438916
  0.72207708 0.80499197 0.79358327 0.74152862]
 [0.04534305 0.59975161 0.15908668 0.9061902  0.94644698 0.34160156
  0.44223161 0.32825623 0.3271705  0.05843313]
 [0.01924366 0.05308424 0.06438004 0.29687785 0.06396771 0.57376771
  0.11578656 0.43866178 0.97361952 0.59467657]
 [0.24018011 0.858972   0.08871078 0.93141721 0.38773261 0.66569346
  0.10490666 0.80060188 0.34004042 0.77168077]
 [0.71826739 0.76912984 0.99739787 0.03612129 0.48970004 0.56174751
  0.17569912 0

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
A = np.random.randint(0,10,50)
print(np.bincount(A).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
C=stride_tricks.as_strided(a,shape=(i,j,n,n),strides=a.strides+a.strides)
print(C)

[[[[0 4 0]
   [2 1 3]
   [2 4 2]]

  [[4 0 0]
   [1 3 4]
   [4 2 3]]

  [[0 0 4]
   [3 4 1]
   [2 3 3]]

  [[0 4 3]
   [4 1 1]
   [3 3 4]]

  [[4 3 2]
   [1 1 3]
   [3 4 2]]

  [[3 2 2]
   [1 3 0]
   [4 2 3]]

  [[2 2 1]
   [3 0 3]
   [2 3 2]]

  [[2 1 0]
   [0 3 1]
   [3 2 2]]]


 [[[2 1 3]
   [2 4 2]
   [3 1 4]]

  [[1 3 4]
   [4 2 3]
   [1 4 3]]

  [[3 4 1]
   [2 3 3]
   [4 3 3]]

  [[4 1 1]
   [3 3 4]
   [3 3 0]]

  [[1 1 3]
   [3 4 2]
   [3 0 3]]

  [[1 3 0]
   [4 2 3]
   [0 3 0]]

  [[3 0 3]
   [2 3 2]
   [3 0 1]]

  [[0 3 1]
   [3 2 2]
   [0 1 2]]]


 [[[2 4 2]
   [3 1 4]
   [3 1 3]]

  [[4 2 3]
   [1 4 3]
   [1 3 0]]

  [[2 3 3]
   [4 3 3]
   [3 0 1]]

  [[3 3 4]
   [3 3 0]
   [0 1 0]]

  [[3 4 2]
   [3 0 3]
   [1 0 0]]

  [[4 2 3]
   [0 3 0]
   [0 0 4]]

  [[2 3 2]
   [3 0 1]
   [0 4 3]]

  [[3 2 2]
   [0 1 2]
   [4 3 0]]]


 [[[3 1 4]
   [3 1 3]
   [3 2 3]]

  [[1 4 3]
   [1 3 0]
   [2 3 3]]

  [[4 3 3]
   [3 0 1]
   [3 3 0]]

  [[3 3 0]
   [0 1 0]
   [3 0 1]]

  [[3 0 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
  def _setitem_(self,index,value):
    i,j = index
    super(Symetric,self)._setitem_((i,j),value)
    super(Symetric,self)._setitem_((j,i),value)

def symetric(A):
  return np.asarray(A + A.T - np.diag(A.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 10  6  3  5]
 [10  4 12  3  6]
 [ 6 12  0 42 13]
 [ 3  3 14  5  8]
 [ 5  6 13  8  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
A=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(A,np.arange(0,A.shape[0],k), axis=0),
                                     np.arange(0,A.shape[1],k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

   
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
A = np.arange(1000)
np.random.shuffle(A)
n=5
print(A[np.argpartition(-A,n)][:n])

[998 997 999 996 995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesion(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)

  ix = np.indices(shape,dtype=int)
  ix = ix.reshape(len(arrays), -1).T

  for n, arr in enumerate(arrays):
    ix[:,n] = arrays[n][ix[:,n]]
    return ix

print(cartesion(([1,2,3],[4,5],[6,7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
a=np.array([('hello',2.5,3),
            ('world',3.6,2)])
R=np.core.records.fromarrays(a.T,
                             names='col1,col2,col3',
                             formats='S8,f8,i8')
print(R)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x=np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.74 s ± 233 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
172 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
162 ms ± 6.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))

C=(A[...,np.newaxis,np.newaxis] ==B)
rows = np.where (C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
A=np.random.randint(0,5,(10,3))
print(A)


[[4 2 2]
 [0 4 0]
 [4 2 4]
 [3 1 0]
 [3 3 2]
 [4 0 3]
 [3 0 1]
 [4 4 2]
 [1 1 2]
 [2 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
a=np.random.randint(0,2,(6,3))
uZ= np.unique(A,axis=0)
print(uZ)

[[0 4 0]
 [1 1 2]
 [2 1 2]
 [3 0 1]
 [3 1 0]
 [3 3 2]
 [4 0 3]
 [4 2 2]
 [4 2 4]
 [4 4 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->',A) # np.sum(A)
np.einsum('i,i->i',A,B) # A*B
np.einsum('i,i',A,B) # np.inner(A,B)
np.einsum('i,j->ij',A,B) #np.outer(A,B)

array([[0.33573561, 0.50309545, 0.28737562, 0.0489616 , 0.28383816,
        0.48297304, 0.2305659 , 0.29085954, 0.36371548, 0.22664441],
       [0.2263904 , 0.33924307, 0.1937807 , 0.03301537, 0.19139535,
        0.32567429, 0.15547325, 0.19612994, 0.24525755, 0.15282894],
       [0.06702271, 0.10043266, 0.05736863, 0.00977418, 0.05666245,
        0.09641564, 0.04602774, 0.05806413, 0.07260832, 0.0452449 ],
       [0.16391126, 0.24561889, 0.14030117, 0.0239038 , 0.13857413,
        0.23579482, 0.11256579, 0.14200207, 0.17757146, 0.11065126],
       [0.07826492, 0.11727897, 0.06699149, 0.01141367, 0.06616686,
        0.11258814, 0.05374831, 0.06780365, 0.08478744, 0.05283415],
       [0.29041405, 0.43518168, 0.24858226, 0.04235218, 0.24552233,
        0.41777563, 0.19944139, 0.25159588, 0.31461687, 0.19604926],
       [0.62734864, 0.94007378, 0.53698416, 0.09148863, 0.53037414,
        0.90247346, 0.43083068, 0.54349413, 0.67963126, 0.42350306],
       [0.38054563, 0.57024268, 0.3257311

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0,r.max(),200)
x_int = np.interp(r_int,r,x)
y_int = np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
x = np.asarray([[1.0,0.0,3.0,8.0],
                [2.0,0.0,1.0,1.0],
                [1.5,2.5,1.0,0.0]])

n=4
M = np.logical_and.reduce(np.mod(x,1)==0,axis=-1)
M &= (x.sum(axis=-1) ==n)
print(x[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
x = np.random.randn(100)
n = 1000
idx = np.random.randint(0,x.size,(n,x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[0.02115392 0.39771778]
